services:
  - type: web
    name: edclean-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        value: sqlite:////data/edapi.db
      - key: EDSTEM_API_URL
        value: https://eu.edstem.org/api
      - key: EDSTEM_API_KEY
        sync: false
      - key: EDSTEM_COURSE_ID
        sync: false
      - key: SYNC_INTERVAL_MINUTES
        value: "360"
      - key: MAX_THREADS_PER_SYNC
        value: "2"

  - type: worker
    name: edclean-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.bot.bot
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        value: sqlite:////data/edapi.db
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EDSTEM_API_URL
        value: https://eu.edstem.org/api
      - key: EDSTEM_API_KEY
        sync: false
      - key: EDSTEM_COURSE_ID
        sync: false

databases:
  - name: edclean-db
    databaseName: edclean
    user: edclean
    plan: free
